/**
 * Every user-facing string of the Bots and Chats feature. `Bot` and `Chat` are provisional
 * names (docs/features/bots-and-chats/README.md, Open); the naming pass changes this file and
 * `routes.ts` and nothing else. English literals, like the other Clisbot sidebar labels.
 */
export const botsCopy = {
  bots: "Bots",
  chats: "Chats",
  newBot: "New bot",
  newBotPlaceholder: "Type a name",
  bot: "Bot",
  chat: "Chat",
  botSettings: "Bot settings",
  chatOptions: "Chat options",
  openInCowork: "Open in cowork",
  archiveBot: "Archive bot",
  deleteChat: "Delete chat",
  addBot: "Add bot",
  rename: "Rename",
  messagePlaceholder: "Message",
  messageBot: (name: string) => `Message ${name}`,
  hostUnavailable: "This Host does not offer bots",
  hostOffline: "This Host is offline",
  noChats: "No chats yet",
  noBots: "No bots yet",
  showMore: "Show more",
  showLess: "Show less",
  working: "Working",
  sessionReplaced: "The bot's session could not resume; a new one was started.",
  form: {
    name: "Name",
    kind: "Kind",
    kindPersonal: "Personal",
    kindTeam: "Team",
    host: "Host",
    launchDefaults: "Launch defaults",
    provider: "Provider",
    model: "Model",
    mode: "Mode",
    thinking: "Thinking",
    defaultMode: "Default mode",
    create: "Create bot",
    save: "Save",
    nameRequired: "Name is required",
    directoryPreview: (slug: string) => `Directory: ${slug}`,
  },
} as const;
