name = "clisbot-website"
account_id = "78ee33c981d5b6b0032d1f5550a5d7ca"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

routes = [
  { pattern = "clisbot.com", custom_domain = true },
  { pattern = "www.clisbot.com", custom_domain = true },
]

[vars]
GA4_DESKTOP_MEASUREMENT_ID = "G-V91TM1TD18"

[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "ff77612425414e4695294410e7c6c2e1"

[[ratelimits]]
name = "DESKTOP_ANALYTICS_LIMITER"
namespace_id = "556929300"
simple = { limit = 120, period = 60 }
