// Differential fixture corpus for the pure functions ported verbatim from
// OpenClaw (formatting, chunking, mentions, targets, error classification).
//
// The corpus is a recording, not a mock: each case names an upstream test file,
// carries the input that upstream test uses, and stores the output the LOCAL
// function produces today. `upstream-differential.test.ts` replays it, so any
// behaviour drift in a ported pure function fails a test even when nobody
// touched the matching `*.test.ts`.
//
// Limitation, on purpose: the recorded output is the local output, never the
// upstream one. Running upstream functions would need a built temp checkout of
// OpenClaw per commit. Regenerating the corpus at a new upstream commit
// therefore diffs local-then against local-now — it tells you a port changed
// behaviour, not that it disagrees with upstream. Verbatim byte fidelity
// against upstream stays `npm run channels:sync:check`'s job.

import { readFileSync } from "node:fs";

/** One recorded call: an input harvested upstream and the local outcome. */
export interface DifferentialCase {
  /** Stable key of the fixture entry. Unique within a channel corpus. */
  readonly id: string;
  /** Upstream test file the input came from, relative to the OpenClaw root. */
  readonly upstreamTestFile: string;
  /** Local function under test, as `<local path>#<export>`. */
  readonly fn: string;
  /** The input, recorded so a reader sees the case without opening the code. */
  readonly input: unknown;
  /** Calls the local function with `input`. Throwing is a recordable outcome. */
  readonly run: () => unknown;
}

/** What the local function did. Throwing is recorded, not swallowed. */
export type DifferentialOutcome =
  | { readonly outcome: "value"; readonly value: unknown }
  | { readonly outcome: "throws"; readonly error: string };

export interface DifferentialFixture {
  readonly id: string;
  readonly upstreamCommit: string;
  readonly upstreamTestFile: string;
  readonly fn: string;
  readonly input: unknown;
  readonly output: DifferentialOutcome;
}

export interface DifferentialCorpus {
  readonly channel: string;
  readonly upstreamRepo: string;
  readonly upstreamCommit: string;
  readonly generatedBy: string;
  readonly note: string;
  readonly cases: readonly DifferentialFixture[];
}

export const DIFFERENTIAL_GENERATOR = "node scripts/channel-differential-fixtures.mjs";

const CORPUS_NOTE =
  "Generated by the differential fixture generator: inputs harvested from the named upstream " +
  "test files, outputs recorded from the LOCAL functions. Regeneration diffs local-then " +
  "against local-now; it does not execute upstream code. Do not edit by hand.";

/**
 * JSON-stable form of an arbitrary value: sorted object keys, and the values
 * `JSON.stringify` silently drops or mangles given an explicit tag. Without
 * this an `undefined` return and a missing property record identically.
 */
export function canonicalizeDifferentialValue(value: unknown): unknown {
  if (value === undefined) return { $undefined: true };
  if (typeof value === "bigint") return { $bigint: value.toString() };
  if (typeof value === "number" && !Number.isFinite(value)) return { $number: String(value) };
  if (typeof value === "function") return { $function: value.name || "anonymous" };
  if (value instanceof Error) return { $error: `${value.name}: ${value.message}` };
  if (value instanceof Map) {
    return {
      $map: [...value].map(([k, v]) => [
        canonicalizeDifferentialValue(k),
        canonicalizeDifferentialValue(v),
      ]),
    };
  }
  if (value instanceof Set) return { $set: [...value].map(canonicalizeDifferentialValue) };
  if (Array.isArray(value)) return value.map(canonicalizeDifferentialValue);
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(record).sort())
      out[key] = canonicalizeDifferentialValue(record[key]);
    return out;
  }
  return value;
}

/** Runs one case and canonicalizes whatever it produced, including a throw. */
export function runDifferentialCase(testCase: DifferentialCase): DifferentialOutcome {
  try {
    return { outcome: "value", value: canonicalizeDifferentialValue(testCase.run()) };
  } catch (error) {
    const message = error instanceof Error ? `${error.name}: ${error.message}` : String(error);
    return { outcome: "throws", error: message };
  }
}

/** Fails loudly on a duplicate id: a silent collision would drop a fixture. */
export function assertUniqueDifferentialIds(cases: readonly DifferentialCase[]): void {
  const seen = new Set<string>();
  const duplicates = new Set<string>();
  for (const testCase of cases) {
    if (seen.has(testCase.id)) duplicates.add(testCase.id);
    seen.add(testCase.id);
  }
  if (duplicates.size > 0) {
    throw new Error(`duplicate differential case id(s): ${[...duplicates].sort().join(", ")}`);
  }
}

export function buildDifferentialCorpus(params: {
  readonly channel: string;
  readonly upstreamRepo: string;
  readonly upstreamCommit: string;
  readonly cases: readonly DifferentialCase[];
}): DifferentialCorpus {
  assertUniqueDifferentialIds(params.cases);
  return {
    channel: params.channel,
    upstreamRepo: params.upstreamRepo,
    upstreamCommit: params.upstreamCommit,
    generatedBy: DIFFERENTIAL_GENERATOR,
    note: CORPUS_NOTE,
    cases: [...params.cases]
      .sort((left, right) => left.id.localeCompare(right.id))
      .map((testCase) => ({
        id: testCase.id,
        upstreamCommit: params.upstreamCommit,
        upstreamTestFile: testCase.upstreamTestFile,
        fn: testCase.fn,
        input: canonicalizeDifferentialValue(testCase.input) ?? null,
        output: runDifferentialCase(testCase),
      })),
  };
}

/**
 * Reads a corpus next to a test module. `readFileSync` rather than a JSON
 * import: the corpus is data the generator owns, not a compiled module, and a
 * JSON import would land it in every consumer's `dist`.
 */
export function readDifferentialCorpus(fileUrl: string | URL): DifferentialCorpus {
  return JSON.parse(readFileSync(fileUrl, "utf8")) as DifferentialCorpus;
}

export interface DifferentialReplayMismatch {
  readonly id: string;
  readonly reason: "missing-case" | "missing-fixture" | "output-changed";
  readonly recorded?: DifferentialOutcome;
  readonly actual?: DifferentialOutcome;
}

/**
 * Replays a recorded corpus against the current local functions. Returns every
 * mismatch rather than throwing on the first, so one run names all the drift.
 */
export function replayDifferentialCorpus(
  corpus: DifferentialCorpus,
  cases: readonly DifferentialCase[],
): readonly DifferentialReplayMismatch[] {
  const byId = new Map(cases.map((testCase) => [testCase.id, testCase]));
  const mismatches: DifferentialReplayMismatch[] = [];
  for (const fixture of corpus.cases) {
    const testCase = byId.get(fixture.id);
    if (!testCase) {
      mismatches.push({ id: fixture.id, reason: "missing-case", recorded: fixture.output });
      continue;
    }
    byId.delete(fixture.id);
    const actual = runDifferentialCase(testCase);
    if (JSON.stringify(actual) !== JSON.stringify(fixture.output)) {
      mismatches.push({
        id: fixture.id,
        reason: "output-changed",
        recorded: fixture.output,
        actual,
      });
    }
  }
  for (const id of byId.keys()) mismatches.push({ id, reason: "missing-fixture" });
  return mismatches;
}
