// Daemon configuration inputs. General provider credentials and executable/runtime
// controls remain available to managed launches and their agent processes.
export const DAEMON_SETTING_ENV_KEYS = [
  "MCP_DEBUG",
  "OPENAI_STT_BASE_URL",
  "OPENAI_TTS_BASE_URL",
  "CLISBOT_ALLOWED_HOSTS",
  "CLISBOT_AGENT_SESSION_STORAGE",
  "CLISBOT_APP_BASE_URL",
  "CLISBOT_BOTS_ENABLED",
  "CLISBOT_COMPOSIO_API_URL",
  "CLISBOT_CONNECTORS_ENABLED",
  "CLISBOT_CORS_ORIGINS",
  "CLISBOT_DICTATION_ENABLED",
  "CLISBOT_DICTATION_LANGUAGE",
  "CLISBOT_DICTATION_LOCAL_STT_MODEL",
  "CLISBOT_DICTATION_STT_PROVIDER",
  "CLISBOT_GIT_CONCURRENCY",
  "CLISBOT_GIT_MAX_PROCESSES_PER_SECOND",
  "CLISBOT_GIT_MAX_PROCESS_CONCURRENCY",
  "CLISBOT_HOSTNAMES",
  "CLISBOT_HUB_PROXY_URL",
  "CLISBOT_LISTEN",
  "CLISBOT_LOCAL_MODELS_DIR",
  "CLISBOT_LOG",
  "CLISBOT_LOG_CONSOLE_FORMAT",
  "CLISBOT_LOG_CONSOLE_LEVEL",
  "CLISBOT_LOG_FILE_LEVEL",
  "CLISBOT_LOG_FILE_PATH",
  "CLISBOT_LOG_FILE_ROTATE_COUNT",
  "CLISBOT_LOG_FILE_ROTATE_SIZE",
  "CLISBOT_LOG_FORMAT",
  "CLISBOT_LOG_LEVEL",
  "CLISBOT_LOG_ROTATE_COUNT",
  "CLISBOT_LOG_ROTATE_SIZE",
  "CLISBOT_PASSWORD",
  "CLISBOT_PROJECT_FOLDERS_ALLOW",
  "CLISBOT_PROJECT_FOLDERS_DENY",
  "CLISBOT_PLUGIN_REGISTRY",
  "CLISBOT_RELAY_ENABLED",
  "CLISBOT_RELAY_ENDPOINT",
  "CLISBOT_RELAY_PUBLIC_ENDPOINT",
  "CLISBOT_RELAY_PUBLIC_USE_TLS",
  "CLISBOT_RELAY_USE_TLS",
  "CLISBOT_SERVICE_PROXY_ENABLED",
  "CLISBOT_SERVICE_PROXY_LISTEN",
  "CLISBOT_SERVICE_PROXY_PUBLIC_BASE_URL",
  "CLISBOT_TRUSTED_PROXIES",
  "CLISBOT_VOICE_LANGUAGE",
  "CLISBOT_VOICE_LLM_PROVIDER",
  "CLISBOT_VOICE_LOCAL_STT_MODEL",
  "CLISBOT_VOICE_LOCAL_TTS_MODEL",
  "CLISBOT_VOICE_LOCAL_TTS_SPEAKER_ID",
  "CLISBOT_VOICE_LOCAL_TTS_SPEED",
  "CLISBOT_VOICE_MODE_ENABLED",
  "CLISBOT_VOICE_STT_PROVIDER",
  "CLISBOT_VOICE_TTS_PROVIDER",
  "CLISBOT_VOICE_TURN_DETECTION_PROVIDER",
  "CLISBOT_WEB_UI_DIST_DIR",
  "CLISBOT_WEB_UI_ENABLED",
  "PORT",
  "STT_CONFIDENCE_THRESHOLD",
  "STT_MODEL",
  "TTS_MODEL",
  "TTS_VOICE",
] as const;

const CONFIG_CONTEXT_ENV_KEYS = [
  "CLISBOT_NODE_ENV",
  "CLISBOT_DESKTOP_MANAGED",
  "OPENAI_API_KEY",
  "OPENAI_BASE_URL",
  "OPENAI_STT_API_KEY",
  "OPENAI_TTS_API_KEY",
] as const;

export function configurationEnvironment(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  return Object.fromEntries(
    [...DAEMON_SETTING_ENV_KEYS, ...CONFIG_CONTEXT_ENV_KEYS].map((key) => [key, env[key]]),
  );
}

export function daemonLaunchEnvironment(input: {
  env: NodeJS.ProcessEnv;
  home: string;
  mode: "managed" | "deployment";
  desktopManaged?: boolean;
}): NodeJS.ProcessEnv {
  const env = { ...input.env };
  if (input.mode === "managed") {
    for (const key of DAEMON_SETTING_ENV_KEYS) delete env[key];
  }
  delete env.CLISBOT_HOST;
  delete env.CLISBOT_DESKTOP_MANAGED;
  env.CLISBOT_HOME = input.home;
  if (input.desktopManaged) env.CLISBOT_DESKTOP_MANAGED = "1";
  return env;
}
