// GENERATED by seam-matrix/generate.mjs — do not edit by hand.
// Static import-graph classification of @openclaw/slack's
// `openclaw/plugin-sdk/*` subpaths against openclaw@2026.7.1-2.
// The loader consumes BOUND_SUBPATHS (the seam) and PASSTHROUGH_SUBPATHS;
// everything else is an unclassified subpath → typed throw at load.

export type SeamClassification = "bound" | "passthrough" | "unsupported";

export interface BoundSubpath {
  hostModule: string;
  hostExports: readonly string[];
  reason: string;
}

export const BOUND_SUBPATHS: Record<string, BoundSubpath> = {
  "openclaw/plugin-sdk/channel-inbound": {
    hostModule: "hosts/channel-inbound.ts",
    hostExports: [
      "dispatchChannelInboundReply",
      "runChannelInboundEvent",
      "runPreparedInboundReply",
      "dispatchReplyFromConfigWithSettledDispatcher",
    ],
    reason:
      "Inbound dispatch to the Hub (plan §7): the vertical's prepared message is handed the host through dispatchChannelInboundReply; the host drives the real agent + relay. The pure normalizers in the same subpath stay OpenClaw's.",
  },
};

export const PASSTHROUGH_SUBPATHS: readonly string[] = [
  "openclaw/plugin-sdk/account-helpers",
  "openclaw/plugin-sdk/account-id",
  "openclaw/plugin-sdk/account-resolution",
  "openclaw/plugin-sdk/agent-runtime",
  "openclaw/plugin-sdk/allow-from",
  "openclaw/plugin-sdk/allowlist-config-edit",
  "openclaw/plugin-sdk/approval-auth-runtime",
  "openclaw/plugin-sdk/approval-client-runtime",
  "openclaw/plugin-sdk/approval-delivery-runtime",
  "openclaw/plugin-sdk/approval-gateway-runtime",
  "openclaw/plugin-sdk/approval-handler-adapter-runtime",
  "openclaw/plugin-sdk/approval-handler-runtime",
  "openclaw/plugin-sdk/approval-native-runtime",
  "openclaw/plugin-sdk/approval-reply-runtime",
  "openclaw/plugin-sdk/boolean-param",
  "openclaw/plugin-sdk/bundled-channel-config-schema",
  "openclaw/plugin-sdk/channel-actions",
  "openclaw/plugin-sdk/channel-config-helpers",
  "openclaw/plugin-sdk/channel-config-writes",
  "openclaw/plugin-sdk/channel-core",
  "openclaw/plugin-sdk/channel-entry-contract",
  "openclaw/plugin-sdk/channel-feedback",
  "openclaw/plugin-sdk/channel-ingress-runtime",
  "openclaw/plugin-sdk/channel-outbound",
  "openclaw/plugin-sdk/channel-pairing",
  "openclaw/plugin-sdk/channel-plugin-common",
  "openclaw/plugin-sdk/channel-policy",
  "openclaw/plugin-sdk/channel-route",
  "openclaw/plugin-sdk/channel-runtime-context",
  "openclaw/plugin-sdk/channel-secret-basic-runtime",
  "openclaw/plugin-sdk/channel-send-result",
  "openclaw/plugin-sdk/channel-status",
  "openclaw/plugin-sdk/channel-targets",
  "openclaw/plugin-sdk/collection-runtime",
  "openclaw/plugin-sdk/command-auth-native",
  "openclaw/plugin-sdk/command-detection",
  "openclaw/plugin-sdk/command-primitives-runtime",
  "openclaw/plugin-sdk/command-surface",
  "openclaw/plugin-sdk/concurrency-runtime",
  "openclaw/plugin-sdk/config-mutation",
  "openclaw/plugin-sdk/context-visibility-runtime",
  "openclaw/plugin-sdk/conversation-runtime",
  "openclaw/plugin-sdk/dangerous-name-runtime",
  "openclaw/plugin-sdk/dedupe-runtime",
  "openclaw/plugin-sdk/directory-config-runtime",
  "openclaw/plugin-sdk/directory-runtime",
  "openclaw/plugin-sdk/error-runtime",
  "openclaw/plugin-sdk/extension-shared",
  "openclaw/plugin-sdk/fetch-runtime",
  "openclaw/plugin-sdk/heartbeat-runtime",
  "openclaw/plugin-sdk/hook-runtime",
  "openclaw/plugin-sdk/host-runtime",
  "openclaw/plugin-sdk/interactive-runtime",
  "openclaw/plugin-sdk/keyed-async-queue",
  "openclaw/plugin-sdk/lazy-runtime",
  "openclaw/plugin-sdk/logging-core",
  "openclaw/plugin-sdk/markdown-table-runtime",
  "openclaw/plugin-sdk/media-mime",
  "openclaw/plugin-sdk/media-runtime",
  "openclaw/plugin-sdk/native-command-config-runtime",
  "openclaw/plugin-sdk/number-runtime",
  "openclaw/plugin-sdk/outbound-media",
  "openclaw/plugin-sdk/pair-loop-guard-runtime",
  "openclaw/plugin-sdk/param-readers",
  "openclaw/plugin-sdk/plugin-config-runtime",
  "openclaw/plugin-sdk/plugin-runtime",
  "openclaw/plugin-sdk/reply-chunking",
  "openclaw/plugin-sdk/reply-history",
  "openclaw/plugin-sdk/reply-payload",
  "openclaw/plugin-sdk/reply-reference",
  "openclaw/plugin-sdk/reply-runtime",
  "openclaw/plugin-sdk/request-url",
  "openclaw/plugin-sdk/routing",
  "openclaw/plugin-sdk/runtime-config-snapshot",
  "openclaw/plugin-sdk/runtime-doctor",
  "openclaw/plugin-sdk/runtime-env",
  "openclaw/plugin-sdk/runtime-fetch",
  "openclaw/plugin-sdk/runtime-group-policy",
  "openclaw/plugin-sdk/runtime-store",
  "openclaw/plugin-sdk/secret-input",
  "openclaw/plugin-sdk/secure-random-runtime",
  "openclaw/plugin-sdk/security-runtime",
  "openclaw/plugin-sdk/session-store-runtime",
  "openclaw/plugin-sdk/setup-runtime",
  "openclaw/plugin-sdk/setup-tools",
  "openclaw/plugin-sdk/ssrf-runtime",
  "openclaw/plugin-sdk/status-helpers",
  "openclaw/plugin-sdk/string-coerce-runtime",
  "openclaw/plugin-sdk/string-normalization-runtime",
  "openclaw/plugin-sdk/system-event-runtime",
  "openclaw/plugin-sdk/target-resolver-runtime",
  "openclaw/plugin-sdk/text-chunking",
  "openclaw/plugin-sdk/text-utility-runtime",
  "openclaw/plugin-sdk/tool-send",
  "openclaw/plugin-sdk/webhook-request-guards",
];

export const SEAM_COUNTS: { bound: number; passthrough: number; unsupported: number } = {
  bound: 1,
  passthrough: 95,
  unsupported: 0,
};

export const IMPORT_CONFORMANCE_MISSING: readonly { spec: string; name: string }[] = [];
